#README - https://docs.microsoft.com/pl-pl/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*

variables:
  vmImage: 'ubuntu-latest'
  envName: 'development'

resources:
  repositories:
    - repository: azure-pipelines-example
      type: git
      name: azure-pipelines-example

stages:
  - template: azure-pipelines/build-stages.yaml@azure-pipelines-example
    parameters:
      vmImage: $(vmImage)
  - template: azure-pipelines/deploy-stages.yaml@azure-pipelines-example
    parameters:
      envName: $(envName)
